# Configurações do perfil de homologação (NÃO coloque dados sensíveis aqui)
spring.profiles.active=hml
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=dbo
spring.sql.init.mode=never
springdoc.swagger-ui.enabled=true
# Datasource será lido das variáveis de ambiente do Azure
